baseurl = "http://learningfromthelegends.com"
title = "Learning from the Legends"
theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
#disqusShortname = "lftl"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-51743090-1"
publishDir = "public"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="menu.home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="menu.instruments"
    name = "Instruments"
    url  = "/img/instruments/instruments_menu_icon.jpg"
    weight = 2

[[menu.main]]
    name       = "Violin"
    identifier = "section.violin"
    url        = "/instruments/violin"
    weight     = 1
    parent     = "menu.instruments"
    post       = 1

[[menu.main]]
    name       = "Trumpet"
    identifier = "section.trumpet"
    url        = "/instruments/trumpet"
    weight     = 2
    parent     = "menu.instruments"
    post       = 2

[[menu.main]]
    name       = "Mendelssohn"
    url        = "/instruments/violin/mendelssohn"
    weight     = 1
    parent     = "section.violin"

[[menu.main]]
    name       = "Bruch"
    url        = "/instruments/violin/bruch"
    weight     = 2
    parent     = "section.violin"

[[menu.main]]
    name       = "Haydn"
    url        = "/instruments/trumpet/haydn"
    weight     = 1
    parent     = "section.trumpet"

[[menu.main]]
    name       = "Hummel"
    url        = "/instruments/trumpet/hummel"
    weight     = 2
    parent     = "section.trumpet"

[[menu.main]]
    identifier="menu.blog"
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    identifier = "menu.faq"
    name = "FAQ"
    url  = "/faq/"
    weight = 4


[[menu.main]]
    identifier = "menu.order"
    name = "Order Now"
    weight = 5

[[menu.main]]
    name       = "For Consumers"
    url        = "/consumers"
    weight     = 1
    parent     = "menu.order"

[[menu.main]]
    name       = "For Educational Institutions"
    url        = "/educators"
    weight     = 2
    parent     = "menu.order"

# Top bar social links menu


[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "https://www.facebook.com/LFTLegends"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/LFTLegends"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Youtube"
    url = "http://www.youtube.com/user/lftlegends"
    pre = "<i class='fab fa-2x fa-youtube'></i>"

[[menu.topbar]]
    weight = 4
    name = "RSS"
    url = "/blog/index.xml"
    pre = "<i class='fas fa-2x fa-rss'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:info@learningfromthelegends.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "LFTL"
    defaultKeywords = ["lftl", "violin", "trumpet"]
    mainSections = ["blog"]
    defaultDescription = "LFTL Website"

    # Social media
    facebook_site = "https://www.facebook.com/LFTLegends" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "LFTLegends" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    #email = "your@email.com"
    #contact_form_ajax = false

    about_us = "<p>Learning from the Legends enables students around the world to reach their highest potential for artistic excellence by providing access to exceptional instructional materials from preeminent teachers and performers while simultaneously providing teachers and performers with a unique opportunity to influence an entire generation of artistic minds. <P> Learning from the Legends will produce the first ever line of instructional videos that encompass the most essential band, orchestral, and choral audition repertoire. These lessons will be taught by the highest echelon of teachers and performers in a professional, organized, and consistent fashion. Our instructional materials will help students perfect their audition skills for the highly competitive admission processes of premier honor ensembles, universities, and conservatories worldwide."
    copyright = "Copyright (c) 2010 - 2019, Learning from the Legends, Ltd.; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>Learning from the Legends Ltd.</strong>
        <br>New York, NY
        <br>
        <strong>USA</strong>
      </p>
      """
    #latitude = "-12.043333"
    #longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

#[params.carousel]
#    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    cols = 2
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.carouselTestimonials]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "Many notable soloists and educators have watched our DVDs and we always like to hear they found them valuable. Have a look what they said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""
