name: hugo publish

on: 
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@v2.1
      with:
        args: -d public/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'hugo publish!'
        force-add: 'true'
        files: public/
