name: hugo publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
        submodules: recursive
    - name: build
      uses: github-actions-x/hugo@master
      with:
        args: -d docs/
    - name: debug
      run: echo ${{ github.ref }} && ls -ali static/img/carousel/
    - name: push
      if: github.ref == 'refs/heads/master'
      uses: github-actions-x/commit@2.1
      with:
        github-token: ${{ secrets.LFTL_Page_Build_Secret }}
        push-branch: 'master'
        commit-message: 'hugo publish!'
        files: docs/
