name: hugo publish

on: [push]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
        submodules: recursive
    - name: build
      uses: github-actions-x/hugo@master
      with:
        args: -d docs/
    - name: debug
      run: echo ${{ github.ref }}
    - name: push
      uses: github-actions-x/commit@2.3
      run: echo "In the push stage" ${{ github.ref }}
      if: github.ref == 'refs/heads/master'
      with:
        github-token: ${{ secrets.LFTL_Page_Build_Secret }}
        push-branch: 'master'
        commit-message: 'hugo publish!'
        files: docs/
